### PR TITLE
Changes with dot.

### PR DESCRIPTION
**Pull request by adammetis**
Changes with dot.

### CODE REVIEW

**Comment by adammetis** [comment]
Metis analyzed your new migrations files. View the results under Pull Requests in the link: 
          https://app.metisdata.io/projects/88851753-e8b7-4fda-b973-259d81c7cedc/test/ca2ee215c2611d6833eb69b4e2cf7a30a317a96a/migration/fcc669fe-a439-4ff2-8098-f3351776a176

**Comment by adammetis** [comment]
Metis test results are available in the link: https://app.metisdata.io/projects/88851753-e8b7-4fda-b973-259d81c7cedc/test/pr:24:Changes%20with%20dot.

**Comment by oshrimy** [comment]
[Metis test results are available here](${encodeURI(
        `${targetUrl}/projects/${jsonRes.api_key_id}/test/${prName}`,
      )})

**Comment by oshrimy** [comment]
[Metis test results are available here](https://www.google.com/projects/1/test.)

**Pull request closed without merging**
